[
	{ 
		"id": 0,
		"name": "SimplyDevio.us", 
		"type": "Website", 
		"work": "Personal Project",
		"description": "Simply Devio.us is a platform for my DeviantART.com-based business, which allows users with no coding or design experience to create their own CSS skins and themes. I currently make $300/month from purchasable downloads. This personal project involved designing and developing a website and mulitiple javascript-based widgets from scratch.",
		"tags": ["JS/jQuery", "HTML5/CSS3", "SASS", "Design", "PHP", "Python", "Responsiveness"],
		"url": "http://www.simplydevio.us/",
		"img": "simplydevious.jpg",
		"main": 0
	},
	{ 
		"id": 1,
		"name": "Translation App", 
		"type": "Website", 
		"work": "Personal Project",
		"description": "This project was an effort to make language learning made easier by providing instant, inline translations for foreign texts. Users can create an account and upload texts to read or browse other texts uploaded by others. Clicking on a word in a text sends an AJAX request to the Yandex translation API and displays a translation above to the word, allowing for a smooth and seamless reading experience. <br><br> All translated words are recorded for the user to later review, edit with a custom translation, or delete. A flashcard function is provided to help users learn any words that haven't been marked as learned. <br><br> This project was a study in Meteor.js, inspired by the difficulty of German class.",
		"tags": ["Meteor.js", "APIs", "JS/jQuery", "MongoDB", "Bootstrap", "HTML5/CSS3"],
		"url": "http://translationapp.meteor.com/",
		"img": "translationapp.gif",
		"img2": "translationapp2.gif",
		"main": 0
	},
	{ 
		"id": 2,
		"name": "SRI-Rice", 
		"type": "Website", 
		"work": "Work",
		"description": "SRI-Rice is an organization at Cornell that is dedicated to spreading knowledge and resources for the System of Rice Intensification (SRI) method, which allows farmers to grow more rice with far less inputs. This project involved working closely with the organization to develop an effective website.<br><br> Still work in progress.",
		"tags": ["Design", "Bootstrap", "HTML5/CSS3", "Git", "Responsiveness"],
		"url": "#",
		"img": "sri.jpg",
		"main": 0
	},
	{ 
		"id": 3,
		"name": "Wanna+", 
		"type": "Website", 
		"work": "Personal Project",
		"description": "Wanna is an online \"Want to Do\" list. Organize, prioritize, and accomplish all those things you never quite got around to doing. The drag-and-drop <a href=\"http://gridster.net/\">Gridster</a> jQuery library was used to create a user-friendly and dynamic to-do list. All styling and design was created from scratch. <br><br>Project was a practice in design and JS/jQuery.",
		"tags": ["JS/jQuery", "Design", "HTML5/CSS3", "SASS"],
		"url": "http://www.simplydevio.us/wanna/",
		"img": "wanna.gif",
		"img2": "wanna2.gif",
		"main": 0
	},

	{ 
		"id": 4,
		"name": "BelleApps", 
		"type": "Website", 
		"work": "Work",
		"description": "Belleapps is a Cornell-based startup that focuses on peer-to-peer food delivery service. This project involved working in a team to design the website and graphics. Bootstrap was integrated for mobile responsiveness. PHP and Javascript was used to create a web application for placing and taking delivery orders.",
		"tags": ["Design", "Bootstrap", "HTML5/CSS3", "JS/jQuery", "PHP", "Git", "Responsiveness"],
		"url": "http://www.belleapps.me/",
		"img": "belleapps.jpg",
		"main": 0
	},
	{ 
		"id": 5,
		"name": "Women in Computing at Cornell", 
		"type": "Website", 
		"work": "Work",
		"description": "WICC is a club at Cornell that aims to empower and support women in computing fields. This project involved completely redesigning an existing website.",
		"tags": ["Design", "HTML5/CSS3", "SASS", "Responsiveness"],
		"url": "http://wicc.acm.org/index.php",
		"img": "prev_wicc.jpg",
		"main": 0
	},
	{ 
		"id": 6,
		"name": "Fiberspark", 
		"type": "Website", 
		"work": "Work",
		"description": "Fiberspark is a Cornell-based startup that offers the fastest and most reliable fiber optic internet in Ithaca. This project involved designing a website from scratch, with an emphasis on clean and clear design.",
		"tags": ["HTML5/CSS3", "Design", "JS/jQuery", "Responsiveness"],
		"url": "http://www.fiberspark.com/",
		"img": "fiberspark.jpg",
		"main": 0
	},
	{ 
		"id": 7,
		"name": "VirusClicker", 
		"type": "Website", 
		"work": "Personal Project",
		"description": "VirusClicker is a time-wasting clicking game inspired by the infamous Cookie Clicker. Click on the virus to infect people, and then buy extra spokes for your virus to infect even more people. <br><br>Project was a quick study in AngularJS.",
		"github": "https://github.com/inyounghong/VirusClicker",
		"tags": ["AngularJS", "JS/jQuery", "HTML5/CSS3", "Design"],
		"url": "http://www.simplydevio.us/VirusClicker/",
		"img": "virusclicker.jpg",
		"main": 0
	},
	{ 
		"id": 8,
		"name": "Fancy Quacks", 
		"type": "CSS Theme", 
		"work": "Commission",
		"description": "FancyQUACKS is a DeviantART journal of artistic ramblings and meditation. This commission involved coding a DeviantART skin with HTML/CSS from Photoshop wireframes. Emphasis was on coding a variety of features while ensuring that the theme remained simple and easy to use by those who might have little web experience.",
		"tags": ["HTML5/CSS3", "Design"],
		"url": "http://puddlefisher.deviantart.com/journal/fancyQUACKS-Issue-no-1-Imaginary-Friends-and-Foes-474389144",
		"img": "fancyquacks.jpg",
		"main": "Web Design"
	},
	{ 
		"id": 9,
		"name": "Virtuoso", 
		"type": "CSS Theme", 
		"installs": 797,
		"description": "Virtuoso is a free DeviantART Skin designed especially for clean, sleek, and professional designs. The aim was to provide a variety of features while ensuring that the skin remained simple to use, even for those without any HTML experience.",
		"tags": ["Design", "HTML5/CSS3"],
		"url": "http://sta.sh/01uzpinlvlhk",
		"img": "virtuoso.jpg",
		"main": "Web Design"
	},
	{ 
		"id": 10,
		"name": "Tincek-Marincek", 
		"type": "CSS Theme", 
		"work": "Commission",
		"description": "With ten Daily Deviations Awards and over 40,000 followers, Tincek-marincek is one of the most famous digital artists on DeviantART. This commission involved converting Photoshop files into a DeviantART profile design and journal theme for Tincek-marincek.",
		"tags": ["HTML5/CSS3", "Design"],
		"url": "http://tincek-marincek.deviantart.com/journal/Threads-Artbook-We-made-it-and-a-DD-495370223",
		"img": "tincek.jpg",
		"main": 0
	},
	{ 
		"id": 11,
		"name": "Tropical Fruit", 
		"type": "CSS Theme", 
		"installs": 1986,
		"description": "Tropical Fruit is a free DeviantART theme with a variety of easily customizable features. With its bright, bold colors, users can create fresh and beautiful designs.",
		"tags": ["Design", "HTML5/CSS3"],
		"url": "http://sta.sh/01e3bkl7f203",
		"img": "tropicalfruit.jpg",
		"main": 0
	},
	{ 
		"id": 12,
		"name": "Forgotten Memories", 
		"type": "CSS Theme", 
		"installs": 3230,
		"description": "Forgotten Memories a free DeviantART theme. It received a Daily Deviation award from <a href='http://www.deviantart.com'>DeviantART</a> on November 2012.",
		"tags": ["Design", "HTML5/CSS3"],
		"url": "http://fav.me/d5ljn3x",
		"img": "memories.jpg",
		"main": 0
	},
	{ 
		"id": 13,
		"name": "Autumn Spirit", 
		"type": "CSS Theme", 
		"installs": 266,
		"description": "Autumn Spirit is a free DeviantART theme. Part of a contest for creating a CSS theme based off an image.",
		"tags": ["Design", "HTML5/CSS3"],
		"url": "http://sta.sh/025qha5bv8qb",
		"img": "autumn.jpg",
		"main": 0
	},
	{ 
		"id": 14,
		"name": "Winter Taste", 
		"type": "CSS Theme", 
		"installs": 631,
		"description": "Winter Taste is a free DeviantART theme.",
		"tags": ["Design", "HTML5/CSS3"],
		"url": "http://sta.sh/0131qo0igmmj",
		"img": "winter.jpg",
		"main": 0
	},
	{ 
		"id": 15,
		"name": "Copper and Stripes", 
		"type": "Graphic Design", 
		"work": "Poster",
		"description": "Poster celebrating my best friend's 19th birthday.",
		"tags": ["Graphic Design", "Illustrator"],
		"img": "copper.png",
		"main": 2
	},
	{ 
		"id": 16,
		"name": "To Kill a Mockingbird", 
		"type": "Typography", 
		"work": "Poster",
		"description": "To Kill a Mockingbird poster.",
		"tags": ["Graphic Design", "Photoshop"],
		"img": "mockingbird.jpg",
		"main": 2
	},
	{
		"id": 17, 
		"name": "Inma Poster", 
		"type": "Graphic Design", 
		"work": "Poster",
		"description": "Poster displaying <a href='http://inma.deviantart.com'>Inma</a>'s artwork.",
		"tags": ["Graphic Design", "Illustrator"],
		"img": "inma.png",
		"main": 2
	},
	{ 
		"id": 18,
		"name": "ObamaCare Infographic", 
		"type": "Graphic Design", 
		"work": "Poster",
		"description": "Infographic poster explaining ObamaCare.",
		"tags": ["Graphic Design", "Illustrator"],
		"img": "obama.jpg",
		"main": 2
	},
	{ 
		"id": 19,
		"name": "BelleApps Icons", 
		"type": "Graphic Design", 
		"work": "Icons",
		"description": "Flat icons for BelleApps website and mobile app.",
		"tags": ["Graphic Design", "Illustrator"],
		"url": "http://www.belleapps.me",
		"img": "belleicons.png",
		"main": 2
	},
	{ 
		"id": 20,
		"name": "Cornell Printers", 
		"type": "Website", 
		"work": "Personal Project",
		"description": "Easy-to-use resource for finding the printers on campus that suit your needs. Provides a Google map and a table that can be filtered by various qualities such as price, black/color ink, etc. Made during Cornell's Big Red Hacks.",
		"github": "https://github.com/inyounghong/inyounghong.github.io",
		"tags": ["AngularJS", "HTML5/CSS3", "Design", "Google Maps API"],
		"url": "http://cornellprinters.co/",
		"img": "printers.jpg",
		"main": 0
	},
	{ 
		"id": 21,
		"name": "Evolution Simulator", 
		"type": "Java Program", 
		"work": "Personal Project",
		"description": "Simulations the evolution of fish over a sequence of generations. The simulation begins with generation 0, where the fish (colored dots) are assigned a random combination of a variety of traits, such as swivel angle, bounce angle, eyesight, inclination to avoid/follow other fish, etc. The \"genes\" of the most fish (the ones that manage to consume the most food) are used to create the next generation of fish, with small mutations. The aim of this project was to eventually lead to the evolution of intelligent fish without explicitly programming an ideal food-searching algorithm for each fish to follow, the same way that evolution manages to create very intricate and effective designs without any intelligent direction.<br><br> Within 10 generations, the fish became mostly homogenous (represented by more similar colors), and there was a noticeable increase in the number of food each fish consumed. However, development tends to stagnate even into further generations, indiciating that perhaps more \"genes\" are needed to produce more intelligent fish.<br><br>Work in Progress project.",
		"tags": ["Java"],
		"url": "#",
		"img": "fishes.jpg",
		"img2": "fishes2.jpg",
		"main": 1
	}
]